---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
 name: "sample-kubernetes-webhook.cfy.cz"
webhooks:
  - name: "sample-kubernetes-webhook.cfy.cz"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["configmaps"]
        scope: "*"
    clientConfig:
      service:
        namespace: local-testing-operator-sdk
        name: sample-kubernetes-webhook
        path: /sample
        port: 9443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lJU3poelNyZ0ZqeHN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2MyVnlkbWxqWlMxallUQWVGdzB5TXpFd01URXdOalV6TWpCYUZ3MHpNekV3TURnd05qVXpNakZhTUJVeApFekFSQmdOVkJBTVRDbk5sY25acFkyVXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURnblV2QjMvTnFJTnM0ODhxN2Z4ZzJ0VmhhYmhRWG9wMCtOWXFrdFBGcW42UnZNQkZ6THVzNGNrcUMKSk1pUjFYaTFsOHI4eGdPR2x3QnQvdm1TdngzOTBmRUU0Q1V5ZTdaRlNnbGRnSFd0ZGdtQzlxRnEvQUhQQi9aZwpUc3JlZ2J3M0JTQkwvYTZua1dmSHlGTWpEN3RNdUtleFZJN1RkQUxhVGMzc2RtYzMyTmJXNUNBa2w2Nmo4UlhDCmVlNlZpSGM5NEJ1d2Ywc21mOCtWdk9LQkE5azdwUkM5SDBjRFJyMzJRVXdKcU1yZmVtK2Q4V28yWjFSdWcvMWkKdWJCbjc5WTlNenRVbU1yTFc0VllWOWFNUGpKTzVpRzRRSHRPNGxIbkpyQVhPcWlSQjBVYzJwQUEzeEZUeXAvdgozVU0zcU85Yk44aGtSa3NxUmh2S0pEK1laY0RQQWdNQkFBR2pZekJoTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTUjFkNFVFT2kxaU5Wa1VWa1VTSTM5Y05CZnFEQWYKQmdOVkhTTUVHREFXZ0JTUjFkNFVFT2kxaU5Wa1VWa1VTSTM5Y05CZnFEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBQnB1MmlwSFEwSkNjaytMclVXbjJjaWYwSE1QQXJBcFNGc25rcmRKb2tEYitaZGVSRm5NMXllb0pBdHU0CjQzellLbGRBTnFyNGwrVjNLeEpEdEk1ekIyeHJHNkJta3BsUElIc0NscHcwTm1XbEg5WXk2Um9NbFZucmwvYVAKN3dXV1d0Q3hMZk5xaStXbk51MlIzVC9LbWtmOGp4a0cwaXFoNEdtR0RPS093cHZnZUZoaWxZejE5Sk55UEk0ZQprcGEvalY5OGRpN0F5T2tHQVpiaDlUZXRUTDRWSm9MN2VXTC9sOWhxR1U2ejZoMDBxaDdrWjc3Y3JRRzR2Uk01CnhZSEpQMnZVRjBNZDJVU3JITHFTaStuNTRDSi9RZVZLQ0R5aWNRa2M2VWQwZ1ZuQUpReTlCRW41WHNPKzA0QVIKMWExYllZVDh4QVhmeUdLSGZybGlOU3lZM2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
