---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
 name: "generic-kubernetes-webhook.cfy.cz"
webhooks:
  - name: "generic-kubernetes-webhook.cfy.cz"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["configmaps"]
        scope: "*"
    clientConfig:
      service:
        namespace: local-testing-operator-sdk
        name: generic-kubernetes-webhook
        path: /sample
        port: 9443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lJY0hDL05Gb0ZWUkl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2MyVnlkbWxqWlMxallUQWVGdzB5TXpFd01UQXhPRFU0TVRCYUZ3MHpNekV3TURjeE9EVTRNVEZhTUJVeApFekFSQmdOVkJBTVRDbk5sY25acFkyVXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM5bTB6TDhzOUpQQ0tCa1pTVFhFMzRRdTlKK3NvMGU5Q29jMVpIK1VMOXVHR3FUMjVGR1pjNHE2TTEKQTZldDNSM1NoM24zK2JWcWRaSlZJdjRWN1E3NER6Z0RuNnhWUS94bHBYdysyWUxzZmNrMTY3OW9PTVF5eXRVbwppZWs3UXZQbGtCN0pMWUc4MWh3ZWtqY284NkN2K1Vmb0s3ZFNoQUdVcFV5WTJ5SzFrQmhVN2JxYjFSUm5kOGc4CmVlRTZaczdwN2RSSjVGSlhFUEN5blBwa3RBZ25CazJwcnZSSHVLQ0Z4eEZUZE5DWVZRTlhxbmhUeHMxY1I4ZGQKQ1AxaUlsT2RWdG1mYlcySDBha21qRFRKbGhGblk3c1E5RElwRGN1bEZ6UGJCMTFLK202OXZaN2ZVV29XMWZtcwpZZFNGRUgvYkpqRWU1QlVjbE5kdFdyck1OSE10QWdNQkFBR2pZekJoTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTUlpDd2V2ejRNQXAyaEFHSS9UWEVYZjBmbjBEQWYKQmdOVkhTTUVHREFXZ0JTUlpDd2V2ejRNQXAyaEFHSS9UWEVYZjBmbjBEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBTXFYU3FJQUJuYm0vT29TQnkwdDI4aU5rVXNTSnFsQ2lWbVgwQldDeWVLUU43eGZDTHZGcWtEdHRDYXJKCjlkNFBQQ3RXMzF5eFI0VlAyQzJsVVpZbnBUeTNSelA4c2RDdy9CNy9MTnRSK2pyYWxiZ2VwR3BUVjdrZjN4WHYKeTA5Y2syTXhIbWg1K2g3OHhTb0I4WHh4b1YyT0R5eTgrYisrWldVZTUrZ3hYRXdaRHFZbi9jcnVPSysxeFVJcgp3NXMzY29lOFI1dUlwYUJqVnpPSXZEZEdqZ2k4UExzV3FGZjYvR1lEOWtWZFZxRXo3QVpaQU16RCtDNWxVWHhvClNuUHdKS1YxK1FsNDZrY1ozSmVpcHNiL0RsVjYrQ240YjJ4RGVIMW0xaXNpWVNkYndqa1JzSy96VUxVQm4wVFkKZkNQNTVmVmc4aTJOems0TVE0cU5EaXR6Nnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
